name: "dry-run-build"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - run: nix build .#nixosConfigurations.oracle-cloud.config.system.build.toplevel --dry-run
    - run: nix build .#nixosConfigurations.laptop.config.system.build.toplevel --dry-run