name: "laptop"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: if ! command -v sudo &> /dev/null; then apt-get update && apt-get install -y sudo; fi
    - uses: cachix/install-nix-action@v25
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        host-keys: 
          - GitHub
          - GitLab
          - BitBucket
    - run: nix build .#nixosConfigurations.laptop.config.system.build.toplevel --dry-run