name: "laptop"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: apt-get update && (command -v sudo || apt-get install -y sudo)
    - uses: cachix/install-nix-action@v25
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: nix build .#nixosConfigurations.laptop.config.system.build.toplevel --dry-run