name: "oracle-cloud"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: if ! command -v sudo &> /dev/null; then apt-get update && apt-get install -y sudo; fi
    - uses: docker/setup-qemu-action@v1
    - uses: cachix/install-nix-action@v25
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        host-keys: 
          - GitHub
          - GitLab
          - BitBucket
    - run: nix build .#nixosConfigurations.oracle-cloud.config.system.build.toplevel --dry-run --option system aarch64-linux --extra-platforms aarch64-linux
