name: "oracle-cloud"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: sudo apt-get update && sudo apt-get install -y qemu-user-static
    - run: nix build .#nixosConfigurations.oracle-cloud.config.system.build.toplevel --dry-run --option system aarch64-linux --extra-platforms aarch64-linux
