name: "oracle-cloud"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v1
    - run: sudo apt update && sudo apt install -y udev
    - uses: cachix/install-nix-action@v25
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: nix build .#nixosConfigurations.oracle-cloud.config.system.build.toplevel --dry-run --option system aarch64-linux --extra-platforms aarch64-linux
