name: "twinkcentre"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: if ! command -v sudo &> /dev/null; then apt-get update && apt-get install -y sudo; fi
    - uses: cachix/install-nix-action@v25
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: nix build .#nixosConfigurations.twinkcentre.config.system.build.toplevel --dry-run
